### ISSUE TITLE
fatal error: sys/queue.h: No such file or directory

### ISSUE THREAD

**Issue by Miaoishappening** [autoas/as#1]
After installed needed libraries from the page "https://autoas.github.io/ssas-public/autosar/2021/12/03/setup.html", I tried to run following command `scons --app=CanSimulator`. It showed me like this: 

![image](https://user-images.githubusercontent.com/57878271/145830863-739f025a-cf74-4744-a732-3ec74e6e75be.png)

The problem is, that i can not install "Sys/queue.h" or bsd-compat-headers on windows, because this batch is for Linux-PC.

Can anyone help me with it?
Thanks :D

**Comment by parai** [comment]
ref this to solve the issue https://packages.msys2.org/package/msys2-runtime-devel

 or manually copy the include/sys/queue.h to c:/msys64/usr/include/sys/queue.h.

**Comment by Miaoishappening** [comment]
Hi, Problem remains the same. The "queue.h" is in the "c:/msys64/usr/include/sys/"...

![image](https://user-images.githubusercontent.com/57878271/146396916-06d8e88b-5af6-4d0f-a07a-c9e006413e3d.png)

And i tried to define system Variable too, but it did not work. 
![image](https://user-images.githubusercontent.com/57878271/146397132-f7517ae8-e976-4c4e-9e15-70c12f20baaa.png)

**Comment by parai** [comment]
I think you didn't know well about compiler. okay ensure patch https://github.com/autoas/ssas-public/commit/d7ce7736350bcaa5a328945aa3583d3bf95f4baa
For those files not found, I think it was very easy to fix it. do some study about GCC compiler.
