### ISSUE TITLE
AsPy库编译错误

### ISSUE THREAD

**Issue by ddleed** [autoas/as#11]
王工,  您好
      感谢您的开源,  我在使用github上最新版本的程序,  编译AsPy库时我遇到了如下错误, 不知如何解决,  请帮忙解答一下,  万分感谢

E:\ssas-public>scons --lib=AsPy
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build\nt\GCC\AsPy
SHLINK build\nt\GCC\AsPy\AsPy.dll
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x23b): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x2db): undefined reference to `PduR_CanTpStartOfReception'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x301): undefined reference to `PduR_CanTpCopyRxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x321): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x33e): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x4e4): undefined reference to `CanIf_Transmit'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x5fc): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x7b7): undefined reference to `PduR_CanTpStartOfReception'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x7dd): undefined reference to `PduR_CanTpCopyRxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x7fd): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x9dc): undefined reference to `PduR_CanTpCopyRxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xa2c): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xaa6): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xaf9): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xca7): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xcde): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xe24): undefined reference to `PduR_CanTpCopyTxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xea4): undefined reference to `CanIf_Transmit'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xed0): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0xf37): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1122): undefined reference to `PduR_CanTpCopyTxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x117f): undefined reference to `CanIf_Transmit'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x120f): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1349): undefined reference to `PduR_CanTpCopyTxData'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x13da): undefined reference to `CanIf_Transmit'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1462): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x15ac): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1614): undefined reference to `CanIf_Transmit'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1650): undefined reference to `PduR_CanTpTxConfirmation'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1cdf): undefined reference to `PduR_CanTpRxIndication'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\prebuilt\libCanTp.a(CanTp.o):CanTp.c:(.text+0x1d11): undefined reference to `PduR_CanTpTxConfirmation'
collect2.exe: error: ld returned 1 exit status
scons: *** [build\nt\GCC\AsPy\AsPy.dll] Error 1
scons: building terminated because of errors.

**Comment by parai** [comment]
double check with this commit https://github.com/autoas/ssas-public/commit/1742fe1070c6c07582973d00083e86dea506165f

**Comment by ddleed** [comment]
我测试OK了, 谢谢!
![image](https://user-images.githubusercontent.com/24479615/173215676-2765ddd7-0fff-4fca-99b5-3849e059ef6a.png)
另外, 这里有一个错误, 应为AsPy.dll
