### ISSUE TITLE
reupload resource asenv.zip

### ISSUE THREAD

**Issue by nhatuan84** [autoas/as#18]
Hi,

Thank for yours work.
Could you please upload : pan.baidu.com asenv.zip
somewhere such as google drive. 

I can not download it.

And how to build under Ubuntu.

Thanks.

**Comment by parai** [comment]
please check this wiki http://autoas.github.io/as/autosar/2018/02/20/as-study-platform.html, and try to setup the study env.

**Comment by antonionehme** [comment]
I have the same problem with the zip...

**Comment by parai** [comment]
Please setup msys2 env by yourself, asenv.zip is not good, it was actually just msys2+anaconda3
