### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by JesseLliang** [autoas/as#18]
![log](https://user-images.githubusercontent.com/35596500/231994196-98d6adad-0574-4e82-a773-3ca1cec7405a.png)
Hi Parai,
I am useing ssas to study Autosar,when I use cmd "scons --app=IsoTpSend" to build the project , there is some mistake occur.Do you Know how can I fix it?thank very much!

**Comment by parai** [comment]
you should uninstall the official python autosar package. Use the one from https://github.com/autoas/arxml
