### ISSUE TITLE
Error when cross compiling

### ISSUE THREAD

**Issue by minhlang102** [autoas/as#24]
Hello, i'm doing cross compile for ARM64 board running Linux. But i got this error. Did i do something wrong?
![image](https://github.com/autoas/ssas-public/assets/85359799/852e3215-19ec-4481-95af-7a821d93a46a)

**Comment by parai** [comment]
you should not specify the "--app" and "--lib" at the same time.

**Comment by minhlang102** [comment]
Hi, i have tried removing --lib, and i got this error. 
![image](https://github.com/autoas/ssas-public/assets/85359799/a712c735-6037-44b9-b1ef-fbfcfa842341)
