### ISSUE TITLE
 No module named 'pyas'

### ISSUE THREAD

**Issue by xiaoma2100** [autoas/as#24]
hi，I cloned the code and I want to run the tools, but I got a error when I run ~/as/com/as.tool/as.one.py$ python3 main.py

I got :

 File "as/com/as.tool/as.one.py/asserial.py", line 25, in <module>
    from pyas.can import *
ModuleNotFoundError: No module named 'pyas'

I think I must build the lua dir, but I did not got how to build that.

BTW: I just start learning AUTOSAR, I have many stupid question, do you have a email or wechat or 微信公众号，so I can ask you.

I found there are so less information on internet, or some book to learning.

**Comment by parai** [comment]
Why don't you look at the README, and check http://autoas.github.io/as/autosar/2018/02/20/as-study-platform.html
