### ISSUE TITLE
stm32f107 can

### ISSUE THREAD

**Issue by goog** [autoas/as#25]
hello, im new to osek, and could you describe the CAN implement idea or map?
i have a question: can i use the **as** as an ECU, AND then read uds CAN data?

**Comment by parai** [comment]
no, please raise issue only about as, this repo doesn't give training. You should study about AUTOSAR CAN stack all by yourself, and this repo can help you to understand the implementation throughly.

**Comment by goog** [comment]
请问现在有没有一个可以支持usb驱动的osek 软硬件系统方案

**Comment by DanielZhang5156** [comment]
哥们，你好。实在没找到好的即时通讯方式，只能在这里给你留言。给你发邮件了请查收一下
