### ISSUE TITLE
About Scheduling and Alarm

### ISSUE THREAD

**Issue by aarisoy** [autoas/as#26]
Hello, 

I am trying to understand your Alarm services and scheduling of task. I have discovered that you schedule your bsw services in 10 ms(generally) but i couldnt find that where do you schedule your tasks. Please help me about that your schedulings.  Up to now, i looked up your SchM.c file and SchM_cfg.h .

**Comment by parai** [comment]
you should check the os configutation, and check the logic of TASK(SchM_Startup) in https://github.com/autoas/as/blob/master/com/as.infrastructure/system/SchM/SchM.c
