### ISSUE TITLE
An error occurs while compiling out the qemu through msys2

### ISSUE THREAD

**Issue by Gayathri280** [autoas/as#28]
it was noted that , for the first time while running 'scons run ' command in console  , it will pop up a msys2 windows which its path is “/as/com/as.tool/qemu”, in which the below 2 command should be executed to compile the qemu out and then install it.
MINGW_INSTALLS=mingw64 makepkg-mingw -sLf
pacman -U mingw-w64-x86_64-qemu-2.10.0-1-any.pkg.tar.xz
 While running the above commands . its throwing an error like 'add  forceline' in a file called wintt.h in winsys2 . 
How to fix this error ? Hope to hear from you soon.

**Comment by F22-raptor** [comment]
I hade the same error , my solution was to start from beginning again on a new virtual machine, now i have an other error in the same step.
