### ISSUE TITLE
how can i solve this problem when compile CanApp

### ISSUE THREAD

**Issue by chenbokaix250** [autoas/as#3]
when I compile CanApp

error：

LINK build\nt\GCC\CanApp\CanApp.exe 
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lSimulator 
collect2.exe: error: ld returned 1 exit status 
scons: *** [build\nt\GCC\CanApp\CanApp.exe] Error 1 
scons: building terminated because of errors.

I don't know how to solve this.

**Comment by parai** [comment]
Thanks,  some source files are missing, add those files by patch [a5e728e9adf6de8f6c6b3b446abb07af903563e7](https://github.com/autoas/ssas-public/commit/a5e728e9adf6de8f6c6b3b446abb07af903563e7)

**Comment by chenbokaix250** [comment]
I added those files，but Still has this problems。

ld.exe: cannot find -lSimulator
