### ISSUE TITLE
Log.cpp and Log.hpp error

### ISSUE THREAD

**Issue by saurabhkumar47** [autoas/as#30]
![2024-02-20 19_02_33-sim-app-boot-tools](https://github.com/autoas/ssas-public/assets/126134385/c2f2e502-3ef9-4220-8d84-a25ad1d5ba3c)

Getting this error while compiling the project for the first time.

**Comment by parai** [comment]
you can try add below code in the "INCLUDE" section to resolve this issue.
```cpp
#include <string>
```

**Comment by saurabhkumar47** [comment]
Thanks,
I added #include `<iostream>` and it worked for me.
Can you help me by telling some way to use this repository to understand AUTOSAR?
