### ISSUE TITLE
No Module name AsPy Error! 

### ISSUE THREAD

**Issue by saurabhkumar47** [autoas/as#31]
![image](https://github.com/autoas/ssas-public/assets/126134385/bfcd7c96-c379-4c1a-9b76-4a6a7f4c45c4)

Error in asone main.py

**Comment by parai** [comment]
AsPy was build out from source. try
```sh
scons --lib=AsPy
```
check the https://github.com/autoas/ssas-public/blob/master/tools/asone/one/__init__.py#L10

**Comment by saurabhkumar47** [comment]
Thanks it worked for me!

**Comment by saurabhkumar47** [comment]
![image](https://github.com/autoas/ssas-public/assets/126134385/11082c78-382f-47cb-9a88-7e8fa7c56762)

Getting above error even after the AsPy.pyd got generated inside the one folder

![image](https://github.com/autoas/ssas-public/assets/126134385/c893b91d-b369-4038-bcb0-4725d4387c53)

**Comment by parai** [comment]
it's the env issue, make sure proper env PATH and PYTHONPATH.
You are on your own to debug and resolve it.
