### ISSUE TITLE
VersatilepbCanApp compile error

### ISSUE THREAD

**Issue by daichenghe** [autoas/as#32]
It raise error when i run [scons --cpl=QemuVersatilepbGCC --app=VersatilepbCanApp] command, the error is:
<img width="1199" alt="1713316340815" src="https://github.com/autoas/ssas-public/assets/41727862/2391ac2e-feef-48c1-b090-fee221a73a8f">
It seems that some c files were not added to the compilation target, I'm not familiar with scons
, how to solve it?
thank you!

**Comment by parai** [comment]
fix with 2 commits:
https://github.com/autoas/ssas-public/commit/b8174bca3741ca071c87c4cb5ffadf82d0775b7f
https://github.com/autoas/qemu/commit/c4495db0212bb899a844e5c5967803edb9c88069
