### ISSUE TITLE
compiling error in scons

### ISSUE THREAD

**Issue by rex1095x** [autoas/as#33]
hello,  when compiling in scons, it reported error as below:
**fnmatch.c:1:1: error: expected identifier or '(' before numeric constant
    1 | 404: Not Found
      | ^~~
make: *** [Makefile:329: fnmatch.o] Error 1
Exception: FAIL of RunCommand "cd E:\030_Programs\Repos\as_master\as\/release/download/dtc & sed -i "s/p_fnmatch(/fnmatch(/g" fnmatch.c & sed -i "s/FNM_NOSYS/2/g" fnmatch.c & sed -i "s/FNM_NORES/3/g" fnmatch.c & sed -i "s/git__tolower/tolower/g" fnmatch.c & sed -i "s/lstat/stat/g" fstree.c & make" = 2:**

so I checked the file in "as\release\download\dtc", the content as below:
fnmatch.h: <a href="/git-for-windows/msys2-runtime/master/include/fnmatch.h">Moved Permanently</a>.
fnmatch.c: 404: Not Found

please help me to fixing this problem, and looking forward to your reply, thanks !

**Comment by parai** [comment]
Now as by default disabled all non autosar related things,  you can get latest code and try again.
