### ISSUE TITLE
Maybe A Compile Error In Linux Ubuntu: Wrong $ASROOT/SConscript ?

### ISSUE THREAD

**Issue by luckyzfl** [autoas/as#34]
Hello, I really appreciate for your work of this AutoSar study platform.
However, when I want to use Ubuntu 16.04 as the host OS for this project, some errors occurred.
One of them is as following:
```
scons: warning: Ignoring missing SConscript 'build/posix/posix/ascore/release/SConscript'
File "/root/as-master/SConscript", line 5, in <module>
TypeError: 'NoneType' object is not iterable:
  File "/root/as-master/SConstruct", line 12:
    objs = SConscript('SConscript',variant_dir=BDIR, duplicate=0)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/root/as-master/SConscript", line 5:
    objs += SConscript('release/SConscript')
```
I guess that is caused by the file Conscript in $ASROOT:
```
5    objs += SConscript('release/SConscript')
``` 
Scons wants to read the file SConscript in  'release/SConscript', but indeed no such file is available in the dir.

At the beginning, I thought some code in as would modify or create such a file, however I did not find such code.

So I modified this line to:
```
5    objs += SConscript('release/ascore/SConscript')
``` 
This works if I want to build the ascore RELEASE.

So my question is: Is that an error? If not, how should I prepare the env to avoid it?

**Comment by parai** [comment]
I forgot the add the related files, issue fixed now
