### ISSUE TITLE
scons run doesnt start the exe due to wpcap dependency on Windows10

### ISSUE THREAD

**Issue by suriavishal** [autoas/as#36]
I have finished building the source and generated the image for x86 machine.

When i try to run the exe it shows the following error

![image](https://user-images.githubusercontent.com/37961088/108550175-30c9be00-7314-11eb-9be2-8688ce749da7.png)

So i got the wpcap.dll and pasted in the relevant folder structure. Then my exe doesnt start and i get the following error

![image](https://user-images.githubusercontent.com/37961088/108550258-53f46d80-7314-11eb-80bc-9c0c090f9406.png)

and my QEMU shows this

![image](https://user-images.githubusercontent.com/37961088/108550292-6373b680-7314-11eb-8cd2-aea2318de334.png)

Please help me out ! Thank you in advance.

**Comment by kayoub5** [comment]
Install WinPcap or Npcap

**Comment by suriavishal** [comment]
@kayoub5 Tried. Still not working
