### ISSUE TITLE
The TX PDU period of Com_Cfg.c is not generated successfully

### ISSUE THREAD

**Issue by wangguoli** [autoas/as#36]
The COM_CONVERT_MS_TO_MAIN_CYCLES is always 1000，will not changed by GenMsgCycleTime which defined in DBC. Because the importDBC module can't generate the CycleTime parameter.

**Comment by parai** [comment]
the Com.py is out of date, this is not an issue for the private version of ssas.
Will plan to update the public, but no promise.

**Comment by parai** [comment]
update the com related https://github.com/autoas/ssas-public/commit/2d8b98b9ea2196c0f4839fe14f9cb11025967efe
