### ISSUE TITLE
Still has that -LSimulator problems

### ISSUE THREAD

**Issue by chenbokaix250** [autoas/as#4]
I added those files，but Still has this problems。

ld.exe: cannot find -lSimulator

_Originally posted by @chenbokaix250 in https://github.com/autoas/ssas-public/issues/3#issuecomment-1001613897_

**Comment by parai** [comment]
thanks, continue to add one missing files by patch https://github.com/autoas/ssas-public/commit/260c9731cf5d7c1c14e33f68a067693731a89c64, please check again

**Comment by chenbokaix250** [comment]
ok it's working 
thanks a lot
