### ISSUE TITLE
Build CanApp problem

### ISSUE THREAD

**Issue by mark870329** [autoas/as#7]
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "D:\ssas-public/tools\building.py", line 73, in <module>
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build\nt\GCC\CanApp
LINK build\nt\GCC\CanApp\CanApp.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Dem/libDem.a(Dem.o):Dem.c:(.text+0x762): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Dem/libDem.a(Dem.o):Dem.c:(.text+0xb10): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x76d): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x797): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x843): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x86d): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x8fd): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0x936): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xa50): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xa7a): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xb26): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xb50): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xc1e): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xc48): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xcd1): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Fls/libFls.a(Fls.o):Fls.c:(.text+0xd24): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xa52): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xaa7): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xab2): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xaf5): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xb23): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xb78): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xb83): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xbc6): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xc25): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xc89): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xd1a): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xd7e): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xdd3): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xe08): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xeb9): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xeee): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xfaa): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xfdf): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0xffa): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0x106e): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0x1089): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\NvM/libNvM.a(NvM.o):NvM.c:(.text+0x10fd): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x80f): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x839): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x8ed): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x917): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x9a5): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0x9de): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xb02): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xb2c): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xbe0): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xc0a): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xcde): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xd08): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xd8f): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Eep/libEep.a(Eep.o):Eep.c:(.text+0xde8): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x5b9): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x5f5): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x688): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x6c4): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x767): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x79a): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x7f7): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x82a): undefined reference to `Std_ExitCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x887): undefined reference to `Std_EnterCritical'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build\nt\GCC\Ea/libEa.a(Ea.o):Ea.c:(.text+0x8ba): undefined reference to `Std_ExitCritical'
collect2.exe: error: ld returned 1 exit status
scons: *** [build\nt\GCC\CanApp\CanApp.exe] Error 1
scons: building terminated because of errors.

I would like ask how to solve this problem, thank you.

**Comment by parai** [comment]
Add 2 missing file by https://github.com/autoas/ssas-public/commit/0ed58765472c02b6b7cc1eebc2da7de710213034

**Comment by mark870329** [comment]
thank you!!!!!!
